Pin Scala sha before new collections merge
When using Scala after the collections merge, with
`sbt 'set every scalaVersion := "2.13.0-pre-6ff3fac"' clean tests/test`,

we get the following error (ditto for current HEAD of 2.13.x, 1c56f0a):

```
[error] /Users/adriaan/git/paradise/tests/src/test/scala/run/Multiple.scala:8: DD is already defined as case class DD
[error]   @doubler @doubler case object D
[error]             ^
java.lang.AssertionError: assertion failed:
  object DD
     while compiling: /Users/adriaan/git/paradise/tests/src/test/scala/run/Multiple.scala
        during phase: typer
     library version: version 2.13.0-pre-6ff3fac
    compiler version: version 2.13.0-pre-6ff3fac
  reconstructed args: -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/classes:/Users/adriaan/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.13.0-pre-6ff3fac.jar -Ywarn-unused-import -deprecation -feature -Xfatal-warnings -classpath /Users/adriaan/git/paradise/tests/target/scala-2.13.0-pre-6ff3fac/test-classes:/Users/adriaan/git/paradise/tests/target/scala-2.13.0-pre-6ff3fac/classes:/Users/adriaan/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.13.0-pre-6ff3fac.jar:/Users/adriaan/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.13.0-pre-6ff3fac.jar:/Users/adriaan/.ivy2/cache/org.scala-lang.modules/scala-xml_2.13.0-pre-6ff3fac/bundles/scala-xml_2.13.0-pre-6ff3fac-1.1.0-newCollectionsBootstrap.jar:/Users/adriaan/.ivy2/cache/jline/jline/jars/jline-2.14.5.jar:/Users/adriaan/.ivy2/cache/junit/junit/jars/junit-4.12.jar:/Users/adriaan/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar:/Users/adriaan/.ivy2/cache/com.novocode/junit-interface/jars/junit-interface-0.11.jar:/Users/adriaan/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar -Xplugin:/Users/adriaan/git/paradise/plugin/target/scala-2.13.0-pre-6ff3fac/paradise_2.13.0-pre-6ff3fac-2.1.0-SNAPSHOT.jar -Ywarn-unused:imports

  last tree to typer: TypeTree(trait Product)
       tree position: line 8 of /Users/adriaan/git/paradise/tests/src/test/scala/run/Multiple.scala
            tree tpe: Product
              symbol: abstract trait Product in package scala
   symbol definition: abstract trait Product extends Any with Equals (a ClassSymbol)
      symbol package: scala
       symbol owners: trait Product
           call site: object DD in class Multiple in package <empty>

== Source file context for tree position ==

     5
     6 @RunWith(classOf[JUnit4])
     7 class Multiple {
     8   @doubler @doubler case object D
     9
    10   @Test
    11   def multiple: Unit = {
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:163)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1970)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1875)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5623)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5682)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5720)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5752)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5693)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5698)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5783)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3144)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3288)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3288)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1996)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1836)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5622)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5682)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5720)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5752)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5693)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5698)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5783)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3144)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3288)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3288)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5330)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5625)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5682)
```